# Generated by Django 5.0.2 on 2024-03-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='student_list',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
